name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      id: run_tests
      run: npm run test:ci
      # Allow preview deployment even if tests fail, but mark the step as failed
      continue-on-error: true
      
    - name: Check test status
      if: steps.run_tests.outcome == 'failure'
      run: |
        echo "::warning::Tests failed but continuing with preview deployment"
        echo "Tests failed - this preview deployment may have issues" >> $GITHUB_STEP_SUMMARY

  deploy-preview:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Deploy to Preview
      id: deploy_preview
      run: |
        URL=$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }})
        echo "preview_url=$URL" >> "$GITHUB_OUTPUT"

    - name: Comment Preview URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `⚠️ Deployed to preview: ${{ steps.deploy_preview.outputs.preview_url }}`
          })
